version: "3.7"

services:
  cryptocurrency_service:
    build: .
    depends_on:
      - postgresql
    ports:
      - 8000:8000
    environment:
       PG_HOST: "postgresql"
       API_VERSION_PREFIX: "/api/v1/"
       REMOTE_NODE_ENDPOINT: "" #specify your node endpoint here
       PRIVATE_KEY_ENCRYPTION_PASS: "" #specify your password for private_key encryption here (see settings.py for more info)

  postgresql:
    image: postgres
    # if you want to keep your data persisted
    #volumes:
    #- cryptocurrency_service_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "cryptocurrency_service"


# if you want to keep your data persisted
#volumes:
#  cryptocurrency_service_db:
