# Generated by Django 4.2.2 on 2023-06-23 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ETH', 'Ethereum')], max_length=10)),
                ('public_key', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
            ],
        ),
    ]
